### ISSUE TITLE
Configuration of inner switches in the AC settings

### ISSUE THREAD

**Issue by dior4ik** [kongkx/homebridge-gree-air-conditioner#1]
Hello,

Is it possible to configure only some of the features in the AC control? For example, I do not want to control the horizontal swing, powerful mode, or dry mode, etc. So, I do not want to have these switches in the AC configuration in my HomeKit device.

Thank you in advance!

**Comment by kongkx** [comment]
Yes. I just publish a new version. You can configure which switches to enable with a commas separated string.

**Comment by ma3too** [comment]
It´s amazing. Works perfectly for me with Sinclair AC
