### ISSUE TITLE
Merge Fan and Vertical Swing into HeaterCooler accessory

### ISSUE THREAD

**Issue by ThisIsQasim** [kongkx/homebridge-gree-air-conditioner#17]
**Is your feature request related to a problem? Please describe:**

Currently the plugin exposes Fan setting and Swing Mode as separate Fan and Switch accessory. This can be consolidated in to the existing `HeaterCooler` accessory.

**Describe the solution you'd like:**

Merge Fan and swing mode characteristics into the `HeaterCooler` accessory. Sample implementation [here](https://github.com/makleso6/homebridge-broadlink-heater-cooler/blob/36b09f4bb5ef7d21a667ee6f8f8a401be6ecf2b5/src/platformAccessory.ts#L113-L119)

**Comment by ThisIsQasim** [comment]
![image](https://user-images.githubusercontent.com/18313886/223690814-7797fa53-f795-42b1-a314-0dce62d609e4.png)


![image](https://user-images.githubusercontent.com/18313886/223690503-6ee321e1-9ec0-4631-9518-e7b15bba5a76.png)

**Comment by kongkx** [comment]
I will check it later, thanks for your info.

Qasim Mehmood ***@***.***>于2023年3月8日 周三18:37写道：

**Comment by ThisIsQasim** [comment]
Thank you for implementing this
