### ISSUE TITLE
Option to set blade positions

### ISSUE THREAD

**Issue by leventesafrany** [kongkx/homebridge-gree-air-conditioner#2]
**Is your feature request related to a problem? Please describe:**
I would like to have the option in apple homekit to set fixed blade positions, especially to change between the automatic swing and the upmost fixed position while automating

**Describe the solution you'd like:**
Can you add a switch for automatic swing or upmost fixed position?

**Describe alternatives you've considered:**
An alternative could be to switch between swing and fixed mode, but this case an option has to be set for where the fixed position should be

**Additional context:**
I have created an automation for when I sleep, the AC turns to silent, low fan speed and stops the swing, but it stops the swing at the position in which it is currently when I start the automation. I would like it to go to the upmost position before it stops the swing

**Comment by kongkx** [comment]
How about I add a “custom configurable” switch that you can configure the values you want in plugins settings ? @leventesafrany

**Comment by leventesafrany** [comment]
That sounds good! Will I be able to configure it to switch between upmost fix position and continuous swing?

**Comment by kongkx** [comment]
Yes, I may also add a default swing position settings.

**Comment by kongkx** [comment]
A new version just published. 

"Default Vertical Swing Mode" is added.  When the  vertical swing switch turn off,  the air conditioner  vertical swing config will set to this default value.

![截屏2021-09-16 下午11 13 11](https://user-images.githubusercontent.com/3049272/133638837-3d7a5cf6-b9c3-46ac-8bd5-ad2363d07947.png)

**Comment by leventesafrany** [comment]
Works perfectly! Thank you!
