### ISSUE TITLE
Toyotomi plug in

### ISSUE THREAD

**Issue by Mitsosxat** [kongkx/homebridge-gree-air-conditioner#4]
Hello, i have a toyotomi air conditioner working with ewpe app. i try to insert it to homekit without success. i tried your plug in inserting the mac address of the device without success. is there any way to succeed?

**Comment by kongkx** [comment]
You may need to find another plugin. Different air conditioner of each brand has different plugin. This plugin is for **Gree** air conditioner only. There are many plugins out there. For example , homebridge-panasonic-air-conditioner for **panasonic**.

**Comment by Mitsosxat** [comment]
The thing is there is no plug in for Toyotomi. I have literally looked everywhere

**Comment by kongkx** [comment]
You may show me your config of homebridge-gree-air-conditioner.  It may has a chance to work make it work, as ewpe and gree seem to using the same protocol.

And you check check this out: https://github.com/stas-demydiuk/ewpe-smart-mqtt

**Comment by Mitsosxat** [comment]
{
            "name": "Toyotomi",
            "language": "en",
            "port": 7002,
            "scanAddress": "192.168.1.255",
            "defaultValue": {
                "statusUpdateInterval": 3,
                "sensorOffset": 40,
                "defaultSpeed": 3,
                "defaultVerticalSwing": 0,
                "defaultHorizontalSwing": 0
            },
            "devices": [
                {
                    "mac": "502cc62bc709",
                    "name": "Toyotomi",
                    "sensorOffset": 40,
                    "defaultSpeed": 3
                }
            ],
            "platform": "GreeAirConditioner"
        }

**Comment by Mitsosxat** [comment]
do you think you can achieve it with your plug in?

**Comment by kongkx** [comment]
I'm not sure as I do not has device to dbug. But I check this  https://github.com/stas-demydiuk/ewpe-smart-mqtt . The network connection method is method is quite alike. 

Can you confirm that `192.168.1.255` is a correct scan address ?  

Bash command example: 

```
ifconfig | grep 192 
```

Result: 

```
inet 192.168.1.102 netmask 0xffffff00 broadcast 192.168.1.255
```

**Comment by Mitsosxat** [comment]
inet 192.168.68.106 netmask 0xffffff00 broadcast 192.168.68.255

**Comment by kongkx** [comment]
update your config:  "scanAddress": "192.168.68.255"  and check if it works

**Comment by Mitsosxat** [comment]
it opens and closes well
